root: ./

structure:
  readme: readme-gitbook.md
  summary: summary-gitbook.md

redirects:
  requirements: ./requirements/requirements-gitbook.md
  architecture: ./architecture/architecture-gitbook.md
  data-structure: ./data-structure/data-structure-gitbook.md
  user-guide: ./user-guide/user-guide-gitbook.md
  deployment: ./deployment/deployment-gitbook.md
  development: ./development/development-gitbook.md
